export{nav, imagePlanet, imageGoology, descriptionTitle, descriptionText, descriptionSource, overview, structure, geology, rotationNumb, revolutionNumb, radiusNumb, averageNumb}
const nav = document.querySelector('nav')
const imagePlanet = document.querySelector('.img-planet')
const imageGoology = document.querySelector('.img-geology')
const descriptionTitle = document.querySelector('.description-title')
const descriptionText = document.querySelector('.description-text')
const descriptionSource = document.querySelector('.description-source a')
const overview = document.querySelector ('.overview')
const structure = document.querySelector ('.structure')
const geology = document.querySelector ('.geology')
const rotationNumb = document.querySelector ('.rotation-numb')
const revolutionNumb = document.querySelector ('.revolution-numb')
const radiusNumb = document.querySelector ('.radius-numb')
const averageNumb = document.querySelector ('.average-numb')